api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
  path( '', views.get_video, name='get_video' ),
  path( 'proxy_get_image', views.proxy_get_image, name='proxy_get_image' ),
  path( 'proxy_get_image/<path:url>', views.proxy_get_image, name='proxy_get_image' ),
  path( 'download', views.download_videos, name='download_videos' ),
  path( 'quit_driver', views.quit_driver, name='quit_driver' ),
]

instagram/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path( "", views.index, name="index" ),
]

prometheus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path( 'admin/', admin.site.urls ),
    path( '', include( 'instagram.urls' ) ),
    path( 'api/', include( 'api.urls' ) ),
]

instagram/models.py
from django.db import models

# Create your models here.

api/views.py
from io import BytesIO
import zipfile
from django.http import HttpResponse, FileResponse
from rest_framework.response import Response
from rest_framework.decorators import api_view
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, NoSuchAttributeException, StaleElementReferenceException, JavascriptException
import requests
import json
from django.urls import reverse

from .web_driver_singleton import WebDriverSingleton
import base64

@api_view(['POST'])
def get_video( request ):
  url = request.body
  """
  get video from posts and reels\n
  return JSON:\n
  {
    name: str,
    profile_picture: str
    video_url: str
  }
  """
  
  url = json.loads( request.body.decode( 'utf-8' ) ).get( 'url' )
  token = request.COOKIES.get('jwt')

  if token != None:
    driver = WebDriverSingleton(token)
    driver.get( url )

  for attempts in range( 3 ):
    try:
      header = driver.find_element( By.TAG_NAME, "header" )
      name = header.find_element( By.XPATH, "//header/div[2]" ).find_element( By.TAG_NAME, "a" )
      profile_picture = header.find_element( By.TAG_NAME, "img" ).get_attribute( "src" )
      video = driver.find_element( By.TAG_NAME, "video" ).get_attribute( "src" )
      
      # video image will show up in DOM when video finish execution
      driver.execute_script( 
        "video = document.querySelector('video');"
        "video.currentTime = video.duration;"
      )
      video_thumbnail = driver.find_element( By.CLASS_NAME, "x5yr21d.xl1xv1r.xh8yej3" ).get_attribute( "src" )
      break
    except ( NoSuchElementException, NoSuchAttributeException ) as e:
      return Response( {'error': f'{ e }'}, status=404 )
    except StaleElementReferenceException:
      continue
    except JavascriptException: # video didn't start automatically, video image element already in DOM
      video_thumbnail = driver.find_element( By.CLASS_NAME, "x5yr21d.xl1xv1r.xh8yej3" ).get_attribute( "src" )
      break
    except Exception as e:
      return Response( { "error": e }, status=500 )

  return Response({
    'name': name.text,
    'profile_picture': base64.urlsafe_b64encode( profile_picture.encode() ).decode(),
    'video_thumbnail': base64.urlsafe_b64encode( video_thumbnail.encode() ).decode(),
    'video_url': video,
    'proxy_server': reverse( 'api:proxy_get_image' )
  })


@api_view(['GET'])
def proxy_get_image( request, url=None ):
  if not url: return HttpResponse( "No URL" )

  image_url = base64.urlsafe_b64decode( url.encode() ).decode()
  response = requests.get( image_url )
  if response.status_code != 200:
    return HttpResponse( "Image not found" )
  
  if ( content_type := response.headers.get( 'Content-Type' ) ) == 'image/jpeg':
    image_content = response.content
    return HttpResponse( image_content, content_type=content_type )
  else:
    return HttpResponse( "Not an image" )
    

@api_view(['POST'])
def download_videos( request ):
  videos = json.loads( request.POST.get('videos', '') )
  if not videos: 
    return Response(status = 404)
  
  zip_path = './instagram/static/Prometheus.zip'
  with zipfile.ZipFile( zip_path, mode="w" ) as zip_file:
    for video in videos:
      name, video_url = video[0], video[1]
      response_object = requests.get( video_url, stream = True )

      # Create a BytesIO object to store the video data
      video_data = BytesIO()

      for chunk in response_object.iter_content( chunk_size=256 ):
        video_data.write( chunk )
      
      zip_file.writestr( ''.join( ( name,'.mp4' ) ), video_data.getvalue() )

  response = FileResponse( open( zip_path, 'rb' ), as_attachment=True, filename="Prometheus.zip" )
  return response


@api_view(['POST'])
def quit_driver( request ):
  token = request.COOKIES.get('jwt')

  if token != None:
    WebDriverSingleton.close_driver(token) #only closes the driver if uuid exists
    return Response()
  else:
    return Response()

instagram/views.py
from api.web_driver_singleton import WebDriverSingleton

from django.shortcuts import render

def index(request):
    token = request.COOKIES.get('jwt')

    if token:
        WebDriverSingleton(str(token))

    return render(request, "instagram/index.html")

instagram/templates/instagram/index.html
{% extends "instagram/layout.html" %}

{% block body %}
  <div class='search_download mb-10'>
    <div class="center">
      <div class="search">
        <input id="url_input" name="input" type="text" placeholder="Paste video URL" autofocus>
        <button id="search_button" data-url="{% url 'api:get_video' %}">
          <svg width="1.5em" height="1.5em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="ui-svg-inline"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"></path></svg>
        </button>
      </div>
    </div>
    
    <div class="videos mt-10">
      
    </div>
    
    <div class="download center">
      <form id="download_form" action="{% url 'api:download_videos' %}" method="post">
        <input id="videos" type="hidden" name="videos" value="">
        <button type="submit">Download videos</button>
      </form>
    </div>

  </div>
{% endblock %}

instagram/templates/instagram/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'instagram/styles.css' %}" rel="stylesheet">
  <title>Prometheus</title>
</head>
<body>
  <header class="mb-10">
      <div class="header-shell">  
        <div class="header-left-side">
          <h1 class="header-quote">
            <i>
              "Prometheus stole fire from the gods and gave it to man. 
              For this, he was chained to a rock and tortured for eternity."
            </i>
          </h1>
          <h1 class="header-catchphrase">
            <i>
              Enjoy the blessing given to you.<br> 
              Give us the link, and we'll bring you your flame.
            </i>
          </h1>
        </div>
        <div class="header-right-side">
          <img class="image_prometheus" src="{% static 'instagram/assets/prometheus.jpg' %}" alt="">
        </div>
      </div>
    </header>

  {% block body %}{% endblock %}

  <p hidden id="quit-driver-path">{% url 'api:quit_driver' %}</p>

  <script src="{% static 'instagram/main.js' %}"></script>
</body>
</html>